### ISSUE TITLE
Enemies stuck behind the wall

### ISSUE THREAD

**Issue by cTux** [IvMov/2dSurviver#1]
Suggest to use better path-finding algorithm.
![image](https://github.com/IvMov/2dSurviver/assets/873220/1c268400-ded8-4967-8aa0-3b9864147fd3)

**Comment by IvMov** [comment]
Thanks, currently I using simple algorithm to move enemy directly in side of player. As I found now - Godot have some internal path finding system - will try to change simple-stupid path finding to this internal path finding.

**Comment by IvMov** [comment]
fixed in 0.0.8 version.
